### ISSUE TITLE
After Actions Report

### ISSUE THREAD

**Issue by blink1073** [blink1073/jupyter_demo#4]
- Used 10 source files from Jon's NPM [branch](https://github.com/jupyter/notebook/commit/62101281e0aeb538b2a5786d83e26c103f60c912), plus styles and codemirror modes.
- Used [jupyter-js-services](https://github.com/jupyter/jupyter-js-services/commit/16173dc58cf2b8bede37f19c9c1d3d3e28cf538c) and jupyter-js-output-area with only one hot-fix
  to jjs
- Needed the latest [dev](https://github.com/jupyter/notebook/commit/66242b9a7029bb46fb52348477affe58bde96142) version of the notebook for cross-origin websocket
- The notebook, the pager, the toolbar, the keyboardmanager all assume a single page application.  The first three use #id lookup, and the latter does not test the event target node.
- Needed to update codecell, completer and tooltip to use new Kernel methods
- Those items should refer to the kernel through the notebook, since it may change
- Actions will need to change for interrupt/restart
- We will need to re-broadcast 'Kernel' and 'Shell' events to be compatible
- The outputarea only handles the rich output, more scaffolding is needed to make it act like the current output area - i.e. the prompt
- Using TypeScript was the only thing that made this demo possible in such a short time
- Estimated 15 hours of work for the notebook-interaction parts of the demo, and 5 hours on scaffolding/styling

**Comment by dwillmer** [comment]
+1 for the TypeScript comment - having the compile-time checks meant API changes from someone else were immediately obvious.
